dataset: davis
batch_size: 256
n_folds: 3
lr: [0.001]
n_epochs: 100
embedding_size: 256
out_dim: [64]
protein_k: [8]
smiles_k: [8]
device: mps

save_folder: ../own_results/davis
patience: 15
start_after: 15

train: False
test: True
method: paper