dataset: kiba
batch_size: 64
n_folds: 3
lr: [0.0001]
n_epochs: 80
embedding_size: 256
out_dim: [128]
protein_k: [8]
smiles_k: [4]
device: mps

save_folder: ../own_results_final/davis_to_kiba_n_epoch_1_test_loader
patience: 10
start_after: 5

train: False
test: True
method: github

batch_ratio: 0.6